### ISSUE TITLE
PCB

### ISSUE THREAD

**Issue by anzejarni** [issalig/toshiba_air_cond#11]
Hi there!
I am interested in the PCB. I might be able to help with the HA feature.

**Comment by issalig** [comment]
Hi, I  can send you one soldered pcb with all the components for 8 EUR. Bare pcb would be 2 EUR.
Postage to Europe would be 2 EUR.

You can PM to  issalig    /AT/   yahoo _DOT_   es

**Comment by issalig** [comment]
Still interested?

**Comment by anzejarni** [comment]
Sorry for the late reply. Sent you an email today.
