### ISSUE TITLE
Hi I have an internal Duct air conditioner Toshiba RAV-SM806BTP-E and I have a question for you in terms of managing it according to your scheme via Wi-Fi can help me with this

### ISSUE THREAD

**Issue by Axab2** [issalig/toshiba_air_cond#13]
Hi I have an internal Duct air conditioner Toshiba RAV-SM806BTP-E and I have a question for you in terms of managing it according to your scheme via Wi-Fi can help me with this

**Comment by Axab2** [comment]
![IMG_20210910_135435__01](https://user-images.githubusercontent.com/108456830/176631397-c3843bb8-48a0-43b4-9c36-0653713e4048.jpg)

**Comment by Axab2** [comment]
Remote only wired to my disappointment

**Comment by Axab2** [comment]
I would be glad if at least there was an opportunity to connect at least an IR receiver to the internal unit to control it with a wireless remote control.

**Comment by Axab2** [comment]
I'm not talking about Wi-Fi at least an IR receiver

**Comment by issalig** [comment]
My project decodes and adapts AB signal to serial 3.3V making it possible to decode/decode messages.

You could skip the Wifi part,and use an IR receiver but you would need a microcontroller such as ESP8266 or also an arduino nano could do the job.

In the board I designed there are still free I/O pins so you can hook a IR receiver.
