### ISSUE TITLE
Operating without a remote wired up? and PCB

### ISSUE THREAD

**Issue by hamishfagg** [issalig/toshiba_air_cond#26]
Hi there,

The instructions for wiring your PCB say to wire it in parallel with a wired remote. Am I able to use just the PCB without also connecting a remote?

Also if you still have some PCBs I'm very interested in getting one :)

Thanks

**Comment by issalig** [comment]
Hi, I have not tried it but afaik it would work. My pcb works independently and it does not depend on the official wire remote.

Yes, I still have some pcbs with components. Cost is 8 EUR + shipping. (I am based in EU)

**Comment by hamishfagg** [comment]
Great, how can I contact you to get one shipped? :)

**Comment by issalig** [comment]
you can write at issalig _AT- yahoo   _DOT-   es
