### ISSUE TITLE
I'm interested in PCB

### ISSUE THREAD

**Issue by krishy2** [issalig/toshiba_air_cond#29]
Hello,

I own a Toshiba Estia heat pump. I'd like to assume it has the same "AB" bus. Do you have any experience? Otherwise I'd give a try, just for fun.

Thanks!

**Comment by issalig** [comment]
Hi, I do not know Estia system, but it would be nice if you can explore it.
I can send you one soldered pcb with all the components for 8.5 EUR. Bare pcb would be 2 EUR.

Postage to Europe would be 2 EUR for untracked.

Tell me which option do you prefer and the destination country.

**Comment by alsig** [comment]
Hey.

 I also have a Toshiba Estia heatpump. 

Do you have more mounted PCBs in stock? Destination country: Denmark 

/Jens

**Comment by issalig** [comment]
Yes. I have the components, so I can mount them in a couple of days.

Also, take into account that I do not know if my PCB is compatible with Estia.

**Comment by krishy2** [comment]
Hey,
Country: HU
Details: kamuzokrishy at gmail

I understand that you are not sure if it works with Estia, but we will figure it out.

**Comment by alsig** [comment]
Super!

Country: Denmark
Details: alsig [at] alsig [dot] dk

**Comment by issalig** [comment]
PM sent.

**Comment by krishy2** [comment]
Hi,
Something went wrong, I have nothing in my mailbox :(

**Comment by alsig** [comment]
Hi, 

Just a bit of feedback.

I've received the PCB two days ago, installed right away and the PCB is working with an Esti heat pump! Great work!

I haven't verified the software yet only the hardware.

I used ESPhome with the following recipe:
```
esphome:
  name: toshiba-link
  friendly_name: toshiba_link

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "magic key :)"

ota:
  password: "top secret password"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Toshiba-Link Fallback Hotspot"
    password: "Yet another password"

captive_portal:

uart:
  tx_pin: D8
  rx_pin: D7
  baud_rate: 2400
  parity: EVEN
  debug:
    direction: RX
    dummy_receiver: true
    after:      
      timeout: 100ms
    sequence:
      - lambda: UARTDebug::log_hex(uart::UART_DIRECTION_RX, bytes, ':');    
```     

So @issalig thank you!
/alsig

**Comment by krishy2** [comment]
I am curious about it!
My office sent me the message that we received it, but I’m working in Africa, so I’ll be at home in 2 weeks.

Please keep me updated!
I’ll try to integrate as well.

Do you have any plan to have a web interface or smartphone app also?

Thanks,
Kris

Tóth Kristóf
Ügyvezető
Tel.: +36-30-2218678
Control Pro Kft.
Irányítástechnikai Tervező és Kivitelező Kft.
1021 Budapest, Ötvös János u. 3.
________________________________

**Comment by issalig** [comment]
Nice, I have not tried ESPHome, in fact I did not know someone had added support for toshiba. I will take a look.

From my side, I have a web interface that resides in the eps8266.
https://github.com/issalig/toshiba_air_cond#software-installation
and it can be found at
https://github.com/issalig/toshiba_air_cond/tree/master/air/data

**Comment by alsig** [comment]
Well there isn't support in esphome, yet. 
All i did was to make a datalogger in esphome. 
I'm hoping that I'll be able to add support to esphome for my heat pump. 
/alsig

**Comment by issalig** [comment]
Feel free to open an issue to report your progress with esphome. Then I could add a small guide in the main page.

**Comment by krishy2** [comment]
Do we know the datagrams of Estia? Or maybe they are the same as other Toshiba products?

From: alsig ***@***.***>
Date: Monday, 2023. June 5. 9:40
To: issalig/toshiba_air_cond ***@***.***>
Cc: Tóth Kristóf ***@***.***>, Author ***@***.***>
Subject: Re: [issalig/toshiba_air_cond] I'm interested in PCB (Issue #29)

Well there isn't support in esphome, yet.
All i did was to make a datalogger in esphome.
I'm hoping that I'll be able to add support to esphome for my heat pump.
/alsig

**Comment by alsig** [comment]
What I can see from the data is the protocol isn't quite the same. There are similarities but the source and destination adresses are different, the checksum calculation doesn't match your implantation and the temperature conversion are also using a different equation...

**Comment by issalig** [comment]
It would be great if you manage to guess the protocol. If you have doubts, just paste the bytes and I can try to guess what´s going on. I tried to document it how I decoded it (main page of repo) but maybe it is not as clear as I though.

You could just ignore crc (at least for RX) . Also you can try https://www.scadacore.com/tools/programming-calculators/online-checksum-calculator/

**Comment by alsig** [comment]
Good evening. 

I have had some success last night and tonight. 

It looks like they have modified the protocol a bit. Here is what I have learned so far.

It looks like the remote control has address 0xA0 and the master has address 0x00. 
The status command is 0x1C and ping/alive is 0x10. All (source, destination, opcode-1 and length) are 8 bits. 
A padding(?) bytes have been inserted in position 4 (zero indexed) and the read/write byte is in position 6.
The checksum is actually a crc16 (info here: https://crccalc.com/?crc=A0001C0F00080000FE03C6C30010845C660000&method=CRC-16/MCRF4XX&datatype=hex&outtype=0) 

I also discovered that the temperature calculations are done like this: 
hex_value = temp_deg_c * 2 + 0x20

I have attached a long file for those of you who are curious.

[logs_toshiba-link_logs_with_timestamps.txt](https://github.com/issalig/toshiba_air_cond/files/11657085/logs_toshiba-link_logs_with_timestamps.txt)

**Comment by issalig** [comment]
Great, it works for the messages starting with A0 but it does not work the others, for example:
 AF:FB:55:C9:FF:DB:7F:CB:FE:FB:F6:FF:B7: (AF:6F) should be  DC:11

**Comment by alsig** [comment]
Damn it :/ Oh well back to the drawing board

**Comment by issalig** [comment]
I have tried reveng to guess the CRC algorithm without success https://reveng.sourceforge.io/

**Comment by issalig** [comment]
Hi, did you finally manage to decode it?

**Comment by alsig** [comment]
Kind of... I did manage to decode part of the protocol but then I got cough up at work and then summer hit... I get back to the project at autumn time. I'll keep you updated...

**Comment by krishy2** [comment]
Hello Guys,

Is there any update at your side?

From: alsig ***@***.***>
Date: Wednesday, 19 July 2023 at 12:02
To: issalig/toshiba_air_cond ***@***.***>
Cc: Tóth Kristóf ***@***.***>, Author ***@***.***>
Subject: Re: [issalig/toshiba_air_cond] I'm interested in PCB (Issue #29)

Kind of... I did manage to decode part of the protocol but then I got cough up at work and then summer hit... I get back to the project at autumn time. I'll keep you updated...

**Comment by issalig** [comment]
I wanted to integrate it with homeassistant but I have not tried yet :)

**Comment by krishy2** [comment]
But the protocol is clear?

In fact, I’d like to change between two modes in my house at the countryside.


  1.  Most of the times I’m away and I want to have 15C VLT just for frost protection. This would allow the best COP.
  2.  When I’m in the house I need the 45C VLT to ramp it up, later 30-35C is ok.

So, I need to change the VLT continuously.  I haven’t found any possibility to achieve this by digital inputs. Even the modbus converter hasn’t Ethernet or wifi, but costs almost 600€.

If the protocol works, I could issue the VLT set command at least. HA can wait 😊

Thanks

From: issalig ***@***.***>
Date: Tuesday, 14 November 2023 at 16:36
To: issalig/toshiba_air_cond ***@***.***>
Cc: Tóth Kristóf ***@***.***>, Author ***@***.***>
Subject: Re: [issalig/toshiba_air_cond] I'm interested in PCB (Issue #29)

I wanted to integrate it with homeassistant but I have not tried yet :)

**Comment by issalig** [comment]
I was referring to my unit not Estias, so nothing from my side.

**Comment by krishy2** [comment]
I’d kill for a Modbus coupler 😊 in that case we could sniff the data.

From: issalig ***@***.***>
Date: Tuesday, 14 November 2023 at 19:28
To: issalig/toshiba_air_cond ***@***.***>
Cc: Tóth Kristóf ***@***.***>, Author ***@***.***>
Subject: Re: [issalig/toshiba_air_cond] I'm interested in PCB (Issue #29)

I was referring to my unit not Estias, so nothing from my side.
