### ISSUE TITLE
Interested in PCB as well.

### ISSUE THREAD

**Issue by sebastianPsm** [issalig/toshiba_air_cond#32]
Hey,

pretty cool project. Do you still have a board for me?

Best greetings
Sebastian

**Comment by issalig** [comment]
Ok, pass me you email and I will contact you.
You can write it here and I will delete it as soon as I read it.

**Comment by sebastianPsm** [comment]
Hey,

My mail address is sebastianpsm@googlemail.com. You can write me in German or English language.

Looking forward to hear from you

Best greetings
Sebastian
