### ISSUE TITLE
Interested in a PCB/Gerber files

### ISSUE THREAD

**Issue by Etacovda** [issalig/toshiba_air_cond#35]
Hi there, 

This look suitable for my r410a series 4 estia - could i get a pcb/files? thanks very much

**Comment by issalig** [comment]
Of course, they are available at https://github.com/issalig/toshiba_air_cond/blob/master/pcb/airpcb_smd/gerber.zip

Also the Kicad files are available, feel free to modify it an to improve it and of course to share it!
