### ISSUE TITLE
Interested in 3 x pcb's if possible?

### ISSUE THREAD

**Issue by prowebuk** [issalig/toshiba_air_cond#39]

**Comment by iti-praia** [comment]
Hi, I'm glad you are interested in the project.
I can send you one soldered pcb with all the components for 8.5 EUR. Bare pcb would be 2 EUR.

Postage to Europe would be 3 EUR for untracked, 8 EUR for tracked.

Tell me which option do you prefer and the destination country.

**Comment by issalig** [comment]
Hi, I'm glad you are interested in the project.
I can send you one soldered pcb with all the components for 8.5 EUR. Bare pcb would be 2 EUR.

Postage to Europe would be 3 EUR for untracked, 8 EUR for tracked.

Tell me which option do you prefer and the destination country.

**Comment by prowebuk** [comment]
Hi,

Can I order 3 x soldered pcb with all the components for 8.5 EUR = 25.50 Euro plus tracked postage @ 8 Euro

My PayPal address is ***@***.******@***.***> if you want to send an invoice?

Address is:

Richard Drage
Proweb (UK) Ltd
Rutland Suite
St James Business Park
Radcliffe on Trent
Nottingham
NG12 2JP
UK

Many thanks

Richard

**Comment by issalig** [comment]
Ok, give me your email address and I will MP you.

**Comment by prowebuk** [comment]
Paypal is ***@***.******@***.***>, not sure what MP is?

Thanks

Richard

**Comment by issalig** [comment]
Sorry, I wanted to say PM (private message).

For some reason I cannot see your address it is shown like this ***@***.******@***.***

Maybe you can try with    your_name AT   your_domain DOT com

**Comment by prowebuk** [comment]
😊 my email is richard at proweb dot net
