### ISSUE TITLE
Interested in 2 PCBs for Australia.

### ISSUE THREAD

**Issue by max-tel** [issalig/toshiba_air_cond#42]
Hello, I love this project and would love your hardware if you have a PCB. I have been looking at WiFi controllers but Toshiba do not have one.

Could I order 2 PCBs, one for myself and one for a friend. 

Thank you!

**Comment by issalig** [comment]
Hey, pass me your email and i Will send you the details.

**Comment by max-tel** [comment]
telfordmax9@gmail.com

thank you!
