### ISSUE TITLE
interested in 4 pcbs - can you send them to the Czech Republic?

### ISSUE THREAD

**Issue by martinskokan** [issalig/toshiba_air_cond#43]
I came across your project and I would like to control the RAS Multisplit system with 4 indoor units. 
would you be so kind and send me the PCBs? payment can be done either through paypal or using direct SEPA transfer

thank you
Martin

**Comment by issalig** [comment]
Do you want just the pcb or also pcb with the components soldered?

**Comment by martinskokan** [comment]
complete with the components please. thanks a lot

ne 18. 2. 2024 v 21:25 odesílatel issalig ***@***.***> napsal:
