### ISSUE TITLE
populated PCBs

### ISSUE THREAD

**Issue by Etacovda** [issalig/toshiba_air_cond#44]
Hi there, I was wondering if you're still doing the populated pcbs?

Thanks,

**Comment by issalig** [comment]
Hi, I still have 2 units available.

**Comment by LuukML** [comment]
Hey, did you sell them already? Im in the netherlands can I order one for testing? Is it esp32?

**Comment by mateuszdrab** [comment]
> Hi, I still have 2 units available.

I'd like one too

**Comment by issalig** [comment]
Sorry guys, I do not longer provide pcbs. But you can get them from jlcpcb.com
