### ISSUE TITLE
Interested in 4 PCBs

### ISSUE THREAD

**Issue by shing6326** [issalig/toshiba_air_cond#45]
Hello, thanks for the great project, I would like to get 4 PCBs for my Toshiba AC, I am located in Singapore.

**Comment by issalig** [comment]
Hi, sorry for the delay.

I only have 2 pcbs available but they are just bare pcbs without components.

**Comment by shing6326** [comment]
Thanks @issalig 

Bare pcbs is fine, I could solder it by myself. May I know if I could have the BOM and CPL files as well for purchasing the components? Feel free to communicate privately with my email for the purchase. Look forward :)

shing
b8452524664@shing.cloud
