### ISSUE TITLE
Interested in 2 populated PCB

### ISSUE THREAD

**Issue by Dieghito72** [issalig/toshiba_air_cond#46]
Hi, I'm interested in 2 populated PCB to be shipped to Italy.

**Comment by issalig** [comment]
Sorry, I do not longer provide pcbs. But you can get them from jlcpcb.com

**Comment by issalig** [comment]
Hi, it's been a long time and you probably have made your own pcbs but I have found in a drawer 2 spare boards in case you are interested.

**Comment by Dieghito72** [comment]
> Hi, it's been a long time and you probably have made your own pcbs but I have found in a drawer 2 spare boards in case you are interested.

Hi! To be honest I'm not so skilled on the electronic parts to go on myself on this, so I'm still interested.

**Comment by issalig** [comment]
Ok, nice. Write me to syxal@tafmail.com and I will give you the details.
